---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: test-dummy-chatbot-13
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-dummy-chatbot-13 
  name: test-dummy-chatbot-13
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi