apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: test-dummy-chatbot-13
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-dummy-chatbot-13 
  name: test-dummy-chatbot-13
spec:
  ports:
  - port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app.kubernetes.io/instance: test-dummy-chatbot-13 
